version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    volumes:
      # to pass config file to prometheus instead of default config
      - ./prometheus_config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
    - "9090:9090"
  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    ports:
    - "9100:9100"
