global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      # based on container name specified in docker-compose file
      - targets: ['prometheus:9090']
    label_limit: 20

  - job_name: 'node-exporter'
    static_configs:
      # based on container name specified in docker-compose file
      - targets: ['node-exporter:9100']
    label_limit: 2
