global:
  scrape_interval:     5s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      # based on container name specified in docker-compose file
      - targets: ['prometheus:9090']
    label_limit: 20

  - job_name: 'node-exporter'
    static_configs:
      # based on container name specified in docker-compose file
      - targets: ['node-exporter:9100']
    label_limit: 2

  - job_name: 'prometheus-example-app'
    static_configs:
      # based on container name specified in docker-compose file
      - targets: ['prometheus-example-app:8080']
    label_limit: 4

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080